MACRO_CONFIG_INT(BotEnable, bot_enable, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: run the bot")
MACRO_CONFIG_STR(BotName, bot_name, 16, "funbot", CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: name the bot plays under")
MACRO_CONFIG_STR(BotOwner, bot_owner, 16, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: name of the player the bot obeys and rescues")
MACRO_CONFIG_INT(BotAutoJoin, bot_auto_join, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: let the bot join by itself once you are on a server")
MACRO_CONFIG_INT(BotDebug, bot_debug, 0, 0, 1, CFGFLAG_CLIENT, "BotSymona: log what the bot is doing once per second")
MACRO_CONFIG_INT(BotRescue, bot_rescue, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: hook and hammer the owner out of freeze")
MACRO_CONFIG_STR(BotFollowName, bot_follow_name, 16, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: name of the player the bot walks after, empty means roam on its own")
MACRO_CONFIG_INT(BotRoam, bot_roam, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: roam around on its own when nobody needs help")
MACRO_CONFIG_INT(BotRoamRadius, bot_roam_radius, 600, 160, 2000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: how far from where it was switched on the bot roams, in pixels")
MACRO_CONFIG_INT(BotHelpAll, bot_help_all, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: rescue any frozen player nearby, not only the owner, admins and listed friends")
MACRO_CONFIG_INT(BotRangedMin, bot_ranged_min, 260, 80, 1200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: below this distance the bot uses hook and hammer instead of shooting, in pixels")
MACRO_CONFIG_INT(BotHelpRange, bot_help_range, 900, 200, 2000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: how far the bot looks for someone to rescue, in pixels")
MACRO_CONFIG_INT(BotFollowDist, bot_follow_dist, 250, 60, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: how far behind the owner the bot hangs while following, in pixels")
MACRO_CONFIG_INT(BotUseHook, bot_use_hook, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: allow pulling the owner out with the hook")
MACRO_CONFIG_INT(BotUseHammer, bot_use_hammer, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: allow hammering the owner out")
MACRO_CONFIG_INT(BotUseLaser, bot_use_laser, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: unfreeze at range with the rifle when the bot has one")
MACRO_CONFIG_INT(BotUseShotgun, bot_use_shotgun, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: drag players out of freeze with the shotgun when the bot has one")
MACRO_CONFIG_INT(BotGentle, bot_gentle, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: walk up and hammer whenever that works instead of reaching for the hook")
MACRO_CONFIG_INT(BotSafePull, bot_safe_pull, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: refuse hook pulls that would land the owner in freeze")
MACRO_CONFIG_INT(BotCrossGaps, bot_cross_gaps, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: take a run-up and jump over narrow freeze strips")
MACRO_CONFIG_INT(BotAvoidFreeze, bot_avoid_freeze, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: never step into freeze, even if that means not reaching the owner")
MACRO_CONFIG_INT(BotPvp, bot_pvp, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: fight players from the war list")
MACRO_CONFIG_INT(BotWarRange, bot_war_range, 700, 200, 2000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: how far the bot detects war enemies, in pixels")
MACRO_CONFIG_INT(BotWarAggro, bot_war_aggro, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: run at the enemy instead of holding position")
MACRO_CONFIG_INT(BotWarWeapon, bot_war_weapon, 0, 0, 4, CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: weapon for war, 0 = auto, 1 = gun, 2 = laser, 3 = grenade, 4 = shotgun")
MACRO_CONFIG_INT(BotWarExecute, bot_war_execute, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: finish off a frozen enemy by pushing it into the deep freeze with the shotgun")
MACRO_CONFIG_INT(BotWarAll, bot_war_all, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: fight anyone who is not the owner, an admin or a listed ally, a war list is not needed")
MACRO_CONFIG_INT(BotAi, bot_ai, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: reply in chat when a local Ollama AI request finishes")
MACRO_CONFIG_STR(BotAiKey, bot_ai_key, 160, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: Ollama API key if the server requires it (usually empty)")
MACRO_CONFIG_STR(BotAiUrl, bot_ai_url, 256, "http://localhost:11434/v1/chat/completions", CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: Ollama OpenAI-compatible chat completions endpoint")
MACRO_CONFIG_STR(BotAiModel, bot_ai_model, 64, "llama3.2", CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: Ollama model name, e.g. llama3.2")
MACRO_CONFIG_STR(BotAiPrompt, bot_ai_prompt, 1024, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "BotSymona: system prompt the AI sees before the tagged message")
